# Matrics multiplaction
**Dr. Mike X Cohen** said to his Linear Algebra Book: "If you write the matrix sizes underneath the matrices, then ma-
trix multiplication is valid only when the two "inner dimensions"
match, and the size of the resulting product matrix is given by
the "outer dimensions." By "inner" and "outer" I’m referring to
the spatial organization of the matrix sizes."
* * Now let's see some Examples ---> A(5x2) multiplication by B(2x7) That's True because two inner dimenctional's are same with together.
* * B(3x4) by multiplication of C(5x3) --> That's worng and you can not multiplicate these.
* * * We use the `@` sign for mutiplaction two or more metrics.


In [8]:
# Now let's make some code with python 
import numpy as np
A = np.array([[2,3,4,5,6,7],
              [4,32,2,56,4,2],
              [3,5,7,1,3,6]])
B = np.array([[3,1,6,2,4,6],
              [0,8,7,0,7,5],
              [3,4,2,1,4,6]])
A.shape,B.shape

((3, 6), (3, 6))

In [11]:
# Now if we multiplay these two matrices we'll have an error because these inner shape are not equal.
res = A@B

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 6)

In [15]:
## Also you could see that's problem. Now I want to transpose B and then multiplay by A 
B_trans = B.T
res = A@B_trans

In [16]:
res

array([[109, 129,  97],
       [196, 308, 228],
       [106, 140,  92]])

#### non-commuitivity 
* Matrics multiplication has not commuitivity `A@B != B@A`, rather they are diffrent's.

In [19]:
non_comm = B_trans@A
non_comm

array([[ 15,  24,  33,  18,  27,  39],
       [ 46, 279,  48, 457,  50,  47],
       [ 46, 252,  52, 424,  70,  68],
       [  7,  11,  15,  11,  15,  20],
       [ 48, 256,  58, 416,  64,  66],
       [ 50, 208,  76, 316,  74,  88]])

In [24]:
# Let's check these two multiplication
print(res.shape == non_comm.shape )
print(" \n\nAlso you cloud see non_commutivity in the matrics multiplication ",)

False
 

Also you cloud see non_commutivity in the matrics multiplication 


### Hadmard matrics multiplication
* Hadmard matrics multiplication is the multiplay element by element.
* * TO the hadmard teorem we use the `*` point.


In [26]:
Ah = np.array([[2,3,4],
               [6,4,3],
               [3,2,1]])
Bh = np.array([[6,5,3],
               [0,1,2],
               [10,2,1]])
Res = Ah * Bh 
print(Res)

[[12 15 12]
 [ 0  4  6]
 [30  4  1]]


* Also you could the hadmard issue to multiplication of two matrics.