### -------------- Fisrt code
### Algorithm
* The goal of this exercise is to create a matrix that contains
the dot products between all pairs of columns in two other
matrices. First, create two 4x2 matrices (that is, 4 rows, 2
columns) of random numbers. Then write a double-for loop
in which you compute the dot products between each column
of both matrices. The i, j element of the resulting matrix will
be the dot product between column i of the first matrix and
column j of the second matrix.


In [20]:
import numpy as np
A = np.random.randn(4,2)
B = np.random.randn(4,2)
Z = np.zeros([2,2])
for coli in range(2):
    for colj in range(2):
        Z[coli,colj] = np.dot(A[:,coli],B[:,colj])
        

In [29]:
print(f'I Columns: {Z[:coli]} \nJ Column: {Z[:colj]}')

I Columns: [[-3.16936026 -3.16588247]] 
J Column: [[-3.16936026 -3.16588247]]


### ------------- Secound Code
### Algorithm --> 
* Create a symmetric matrix by optional 
numbers matrix and applying three matrix operations: convert
to triangular, transpose, matrix addition.
* Symetric matrics formula: symetrics, `A = A^T`
* Add sym= `1/2(A^T+B)` and Multi sym = `A^T*A`

In [37]:
A = np.array([[3,4],[5,6]])
Addsym = 1/2*(A.T+A) ## Add formula
Multsym = A.T*A
Addsym

array([[3. , 4.5],
       [4.5, 6. ]])

In [39]:
Multsym

array([[ 9, 20],
       [20, 36]])

In [40]:
At = np.tril(A)
At

array([[3, 0],
       [5, 6]])

### ------------ Third Code
### Algorithm
* .Create a diagonal matrix of size 4x8 without using the diag()
function. The diagonal elements should be 1,2,3,4. How much
of your code would you need to change to create an 8x4 diagonal matrix?


In [43]:
D = np.ones((4,8))
for d in range (min(D.shape)):
    D[d,d] = d+1
D    

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 1., 1., 1., 1., 1.],
       [1., 1., 3., 1., 1., 1., 1., 1.],
       [1., 1., 1., 4., 1., 1., 1., 1.]])

In [42]:
D = np . z e r o s ( ( 4 , 8 ) )
f o r d i n r an ge ( min (D. shape ) ) :
D[ d , d ] = d+1


SyntaxError: invalid syntax (2793932555.py, line 1)