In [2]:
# Frist practice 
# create vector by orentation
import numpy as np
lists = [1,2,3,4]
array = np.array([2,1,3,4,5])
"""Array No orentation""" 
column = np.array([[[3],[1],[6],[8]],[[2],[1],[4],[9]]])
'''Column  vector'''
row = np.array([[2,3,4,5,6,7],[2,1,3,4,4,2]])
'''Row vector'''
lists,' ------ ',array,' ----- ',column,' ------ ',row

([1, 2, 3, 4],
 ' ------ ',
 array([2, 1, 3, 4, 5]),
 ' ----- ',
 array([[[3],
         [1],
         [6],
         [8]],
 
        [[2],
         [1],
         [4],
         [9]]]),
 ' ------ ',
 array([[2, 3, 4, 5, 6, 7],
        [2, 1, 3, 4, 4, 2]]))

### NUMBER OF DIMENSIONAL
Now If we want to see our `number of dimensional` we use the `.ndim` 

In [3]:
# IF you see we can not use the (lists.ndim) because list object has not attribute by the name of 'ndim'
# lists.ndim // Error
column.ndim

3

### Transpose vector
You can transform a column vector to a row vector by transposing it, convert columns to row, and row to columns, by using the `.T`  

In [4]:
row

array([[2, 3, 4, 5, 6, 7],
       [2, 1, 3, 4, 4, 2]])

In [5]:
transpose = row

In [6]:
transpose

array([[2, 3, 4, 5, 6, 7],
       [2, 1, 3, 4, 4, 2]])

In [7]:
transpose.T,'This is our Transposing vector from row to column '

(array([[2, 2],
        [3, 1],
        [4, 3],
        [5, 4],
        [6, 4],
        [7, 2]]),
 'This is our Transposing vector from row to column ')

In [8]:
### Double transposing a vector leaves its orenattion unchanged
transpose.T,' ----- ',transpose.T.T

(array([[2, 2],
        [3, 1],
        [4, 3],
        [5, 4],
        [6, 4],
        [7, 2]]),
 ' ----- ',
 array([[2, 3, 4, 5, 6, 7],
        [2, 1, 3, 4, 4, 2]]))

# Scaler multiplaction
Scaler-multipalction is achieved by multiplying each element of the vector by the scalar, for scalar a and vector v1 this is the formal definition.....
`av = [a*v1,a*v2,a*v3......a*vn].T`

In [9]:
### basic code  by opeatrions (adding, subtracting, multiplaction) is straighforward.
v1 = np.array([2,3,4])
v2 = np.array([6,4,3])
v3 = 4*v1-3*v2
4*v1,'...............',3*v2,'.......',v3

(array([ 8, 12, 16]),
 '...............',
 array([18, 12,  9]),
 '.......',
 array([-10,   0,   7]))

### Vector dot product
The dot product is a single number that provide information about the relationship between two vectors.

In [10]:
dot1 = np.array([2,3,4,5])
dot2 = np.array([6,5,4,3])
result = np.dot(dot1,dot2)
print(result)

58
