### Matrixes
* matrix def: it is a colection of row and columns. which we represent row by i and cloumns by j
* [[12,3,4,],
* [2,3,45,5]] i*j


# Transposing of a matrix 
* I gave some discribtion about traspossing of a vector this is alse same like vector transpos: also we swap row for column and vice-versa
* formula == `Bi*j = Bj*i`

In [2]:
import numpy as np
A = np.random.randn(2,5)
print(A)

[[-1.94852662 -0.85492978 -0.07486012  0.43216484 -1.06746749]
 [-0.99992869  1.22919722 -0.32180093  2.40735924 -0.1980137 ]]


In [3]:
# Then we transposed our 2*5 matrix to 5*2 matrix
At = A.T
print(At)

[[-1.94852662 -0.99992869]
 [-0.85492978  1.22919722]
 [-0.07486012 -0.32180093]
 [ 0.43216484  2.40735924]
 [-1.06746749 -0.1980137 ]]


## identity matrix
* The identity matrix is the matrix equalent of the number 1, in that any number x times i is x(X*1=X).
* IF we want to represent the identity matrix in the computer we use the `eye` postface

In [4]:
a = 4
IdentityMatrix = np.eye(4)
print(IdentityMatrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Zeros matrix
* The zeros matrix is a matrix of al zeros.
* The zeros matrix is indecated by 0.
* Zeros matrix can be square or rectangular.

In [5]:
z = 5 # Rows
e = 3 # columns
zeroMatrix = np.zeros((z,e))
print(zeroMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Diagonal matrix
* A diagonal matrix has all zros in the off-diagonals,and only the diagonal elements.
* And we represent the diagonal matrix to D

In [6]:
D = np.diag([1,2,3,4])
R = np.random.randn(3,4)
d = np.diag(R);
print(d)

[ 0.32560716 -0.08455291  0.41174419]


### Agumented matrix
* An agumented matrix is the result of concatnating two or more matrices.
* when we work on python we use the `concatenate` post-face

In [7]:
AG = np.random.randn(3,5)
BG = np.random.randn(3,6)
AGconBG = np.concatenate((AG,BG),axis = 1)
print(AG)

[[ 1.35161973 -0.19189227 -1.97911667 -0.73856027 -0.56663346]
 [-0.85866155 -1.29884508 -0.28872707 -1.7023091  -0.11577703]
 [-1.17721019  1.11855207  0.21631963  0.72727529 -1.20022252]]


In [8]:
print(BG)

[[-1.90143351 -0.96236569 -1.73748596 -0.64685404 -1.25818196 -0.65931619]
 [-0.16824183  0.65507492  1.33751959 -1.17442671 -0.83609923  0.06859802]
 [ 2.4224376   1.2688919   0.66844731  0.2450687   0.81133454  2.21395098]]


In [9]:
print(AGconBG)

[[ 1.35161973 -0.19189227 -1.97911667 -0.73856027 -0.56663346 -1.90143351
  -0.96236569 -1.73748596 -0.64685404 -1.25818196 -0.65931619]
 [-0.85866155 -1.29884508 -0.28872707 -1.7023091  -0.11577703 -0.16824183
   0.65507492  1.33751959 -1.17442671 -0.83609923  0.06859802]
 [-1.17721019  1.11855207  0.21631963  0.72727529 -1.20022252  2.4224376
   1.2688919   0.66844731  0.2450687   0.81133454  2.21395098]]


### Trangular matrix
* is a half-way between a diagonal and full matrices.
* IT is devided in two part Upper trangular and lower trangular, to get more information you can reject to linear algebra book
* `tril` extract the lower trangular
* `triu` extract the upper trangular

In [10]:
T = np.random.randn(4,4)
lower = np.tril(T)
upper = np.triu(T)
print(lower)

[[-1.8502818   0.          0.          0.        ]
 [ 1.14369339  1.47526727  0.          0.        ]
 [-0.367963   -0.6093797  -0.72438215  0.        ]
 [-0.63156399 -0.16096433 -2.10031028 -3.13838379]]


In [11]:
print(T)

[[-1.8502818  -0.20572045 -0.37452863  0.05268902]
 [ 1.14369339  1.47526727  0.05473967 -0.71700064]
 [-0.367963   -0.6093797  -0.72438215 -0.19394845]
 [-0.63156399 -0.16096433 -2.10031028 -3.13838379]]


In [12]:
print(upper)

[[-1.8502818  -0.20572045 -0.37452863  0.05268902]
 [ 0.          1.47526727  0.05473967 -0.71700064]
 [ 0.          0.         -0.72438215 -0.19394845]
 [ 0.          0.          0.         -3.13838379]]


### Addition of a matrix
*  For addition to be a valid operation, both matricesmust be the same size— M×N —and the resulting matrix will also be M × N
* ci,j = ai,j + bi,j

In [19]:
Amat = np.array([[2,3],
                 [4,3]])
Bmat = np.array([[3,4],
                 [3,2]])
resultOfMatrix = Amat+Bmat
Amat.shape,Bmat.shape

((2, 2), (2, 2))

In [21]:
print(f'A matrix \n{Amat},\n\nB matrix \n{Bmat}')

A matrix 
[[2 3]
 [4 3]],

B matrix 
[[3 4]
 [3 2]]


In [22]:
print(f"The resutl of our matrix \n{resultOfMatrix}")

The resutl of our matrix 
[[5 7]
 [7 5]]


## Scaler Mutiplacation of a matrix
* scalar-matrix multiplication means to multiply a matrix by a single number.
* to the scaler-matrix multiplication our dimenctional not changeble.

In [31]:
Amat = np.array([[2,3],
                 [4,3],
                 [2,4]])
scaler = 3
resultOfMatrixMulti = Amat*scaler
Amat.shape

(3, 2)

In [32]:
print(resultOfMatrixMulti)

[[ 6  9]
 [12  9]
 [ 6 12]]


# shifting a matrix
* We can combine matrix addition with scalar-matrix multiplicationto apply a procedure called "shifting" a matrix.
* To "shift" a matrixmeans to add to the matrix a multiple of the identity matrix.
* This is the shiftting a matrix fourmula: `A' = A + λI`

In [36]:
lemda = 0.2
I = np.eye(4)
shifittingMatrix = np.random.randn(4,4)
sheftting = shifittingMatrix + I*lemda
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
print(shifittingMatrix)

[[-0.54642999 -0.33231213  2.84514709 -1.05107428]
 [-0.36888511  0.54442207 -0.3787618   0.30848649]
 [ 0.49618083  0.751775    0.50506094 -0.86466269]
 [ 0.7554162   0.28911285  0.25172655  1.63371705]]


In [38]:
print(sheftting)

[[-0.34642999 -0.33231213  2.84514709 -1.05107428]
 [-0.36888511  0.74442207 -0.3787618   0.30848649]
 [ 0.49618083  0.751775    0.70506094 -0.86466269]
 [ 0.7554162   0.28911285  0.25172655  1.83371705]]


### Trace
* The trace is an operation that produces a single number from a squre matrix.
*   it is indecated to tr(A).
*   The trace operation has two applications in machine learning: It is used to compute the Frobenius norm of a matrix (a measure of the
 magnitude of a matrix) and it is used to measure the "distance" between two matrices.
* The trace is defined only for square matrices

In [42]:
Matrix = np.random.randn(4,4)
traces = np.trace(Matrix)
Matrix

array([[ 0.19040792,  1.02943813,  0.98059362, -1.00240246],
       [ 0.14511983,  1.4982394 , -0.95168572,  0.62882005],
       [ 0.11311835, -1.76186541,  1.0014182 , -0.42522167],
       [-1.23711321, -0.16255353, -1.35126219, -1.35068858]])

In [43]:
print(traces)

1.33937693902386
