In [2]:
import numpy as np


### Linear weighted combination
simply means scaler-vector multiplaction and addition: Take some set of vectors, multiply each vector by any scaler, and add them to produce a `single vector` 

In [7]:
w = [3,4,5]
v1 = np.array([2,3,4])
v2 = np.array([5,4,3])
v3 = np.array([9,5,3])
result = w[0]*v1 + w[1]*v2 + w[2]*v3
print("This is new vector: ",result)

This is new vector:  [71 50 39]


### Outer-product 
the outer product is a way of combining two vector to produce a matrics, and this is the outer product fourmula: `v` and `w` are vectors and `M`,`N` are the size of row and columns then we calcualte by this fourmula Outer product: `v*w^T = M X N`. Essentially, the dot product and outer product are special cases of matrix `multiplaction`

In [8]:
### Now we use the simply way to find the outer product with numpy library
a1 = np.array([3,4,5])
b1 = np.array([4,5,6])
result = np.outer(a1,b1)
print(result)

[[12 15 18]
 [16 20 24]
 [20 25 30]]


### Unit vector
*** it is often useful to have a vector with a length of one: `||V|| = 1`.
Unit vector also allow for creating a spcial kind of matrix called orthogonal matrix.
imporantly, The direction of thevectors dose not changable.

In [11]:
uV = np.array([4,3,2,1])
vMag = np.linalg.norm(uV)
print(f'vMag: {vMag}')

vMag: 5.477225575051661
